# Generated by Django 3.2.10 on 2021-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211229_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='scale',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
