# Generated by Django 3.2.10 on 2021-12-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companies_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='companies',
            name='scale',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='companies',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
