# Generated by Django 3.2.10 on 2022-01-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211230_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Startups',
        ),
    ]
